services:
  server:
    build: ../server
    environment:
      - NODE_ENV=production
    ports:
        - "5000:5000"
    env_file:
      - ../server/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: projet_crypto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - postgres_crypto_data:/var/lib/postgresql/data

  #victim:
  #  build: ../victim
  #  entrypoint: /bin/bash
  #  stdin_open: true
  #  tty: true

volumes:
  postgres_crypto_data:
